# Generated by Django 5.2.5 on 2025-11-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='milk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sweetness',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
