# Generated by Django 5.2.5 on 2025-11-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_orderitem_milk_orderitem_size_orderitem_sweetness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Coffee'), ('pastry', 'Pastry'), ('other', 'Other'), ('iced & chilled concoctions', 'Iced & Chilled Concoctions')], max_length=50),
        ),
    ]
