# Generated by Django 5.2.5 on 2025-11-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
