# Generated by Django 5.2.5 on 2025-11-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('card', 'Card')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studyroombooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('card', 'Card')], max_length=10, null=True),
        ),
    ]
