# Generated by Django 5.2.5 on 2025-11-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_order_payment_method_studyroombooking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroombooking',
            name='time_slot',
            field=models.CharField(max_length=100),
        ),
    ]
