# Generated by Django 5.2.5 on 2025-11-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_alter_studyroombooking_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Coffees and Pastries', 'Coffees and Pastries'), ('Non-Coffees', 'Non-Coffees'), ("Barista's Specials", "Barista's Specials")], max_length=50),
        ),
    ]
